In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
%matplotlib inline

In [3]:
df = pd.read_csv('nasa.csv')
df.head()

Neo Reference ID     Name  Absolute Magnitude  Est Dia in KM(min)  \
0           3703080  3703080                21.6            0.127220   
1           3723955  3723955                21.3            0.146068   
2           2446862  2446862                20.3            0.231502   
3           3092506  3092506                27.4            0.008801   
4           3514799  3514799                21.6            0.127220   

   Est Dia in KM(max)  Est Dia in M(min)  Est Dia in M(max)  \
0            0.284472         127.219879         284.472297   
1            0.326618         146.067964         326.617897   
2            0.517654         231.502122         517.654482   
3            0.019681           8.801465          19.680675   
4            0.284472         127.219879         284.472297   

   Est Dia in Miles(min)  Est Dia in Miles(max)  Est Dia in Feet(min)  ...  \
0               0.079051               0.176763            417.388066  ...   
1               0.090762               0.202951            479.225620  ...   
2               0.143849               0.321655            759.521423  ...   
3               0.005469               0.012229             28.876199  ...   
4               0.079051               0.176763            417.388066  ...   

   Asc Node Longitude Orbital Period  Perihelion Distance  Perihelion Arg  \
0          314.373913     609.599786             0.808259       57.257470   
1          136.717242     425.869294             0.718200      313.091975   
2          259.475979     643.580228             0.950791      248.415038   
3           57.173266     514.082140             0.983902       18.707701   
4           84.629307     495.597821             0.967687      158.263596   

   Aphelion Dist  Perihelion Time  Mean Anomaly  Mean Motion  Equinox  \
0       2.005764     2.458162e+06    264.837533     0.590551    J2000   
1       1.497352     2.457795e+06    173.741112     0.845330    J2000   
2       1.966857     2.458120e+06    292.893654     0.559371    J2000   
3       1.527904     2.457902e+06     68.741007     0.700277    J2000   
4       1.483543     2.457814e+06    135.142133     0.726395    J2000   

   Hazardous  
0       True  
1      False  
2       True  
3      False  
4       True  

[5 rows x 40 columns]

In [7]:
# Discard columns with identical values, identifiers, etc.
X = df[['Absolute Magnitude', 'Est Dia in Feet(min)', 'Est Dia in Feet(max)', 'Epoch Date Close Approach', 'Relative Velocity km per hr', 'Miles per hour','Miss Dist.(miles)','Orbit Uncertainity','Minimum Orbit Intersection', 'Jupiter Tisserand Invariant','Epoch Osculation', 'Eccentricity', 'Semi Major Axis', 'Inclination','Asc Node Longitude', 'Orbital Period', 'Perihelion Distance','Perihelion Arg', 'Aphelion Dist', 'Perihelion Time', 'Mean Anomaly','Mean Motion']]
#X[0:5]

X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[-0.23104209, -0.20941058, -0.20941058, -1.97308738, -1.07713904,
        -1.07713904,  1.11607503,  0.48182219, -0.63171955, -0.34104856,
         0.3009042 ,  0.23821558,  0.01287488, -0.67195451,  1.37719066,
        -0.07004915, -0.02117222, -1.22388641,  0.01957056,  0.45919023,
         0.77839321, -0.43110028],
       [-0.33482448, -0.15840557, -0.15840557, -1.97308738,  0.56814611,
         0.56814611,  0.8659215 , -0.167955  ,  1.15865026,  0.3239018 ,
         0.3009042 , -0.17123418, -0.5580782 ,  1.37531503, -0.3431925 ,
        -0.56539287, -0.39326705,  1.24789699, -0.51480172,  0.07081791,
        -0.06909298,  0.31258164],
       [-0.68076581,  0.07278876,  0.07278876, -1.97003488, -0.8748918 ,
        -0.8748918 , -1.41184277, -1.14262078, -0.43484356, -0.40326142,
         0.3009042 , -0.19022296,  0.11173524, -0.83546712,  0.84557267,
         0.02156329,  0.56772222,  0.62301108, -0.02132314,  0.41557933,
         1.03940428, -0.52211437],
       [ 1.77541761

In [8]:
y = df['Hazardous'].values
y[0:5]

array([ True, False,  True, False,  True])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (3280, 22) (3280,)
Test set: (1407, 22) (1407,)


In [10]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train)
neighbors

KNeighborsClassifier(n_neighbors=3)

In [11]:
# Predict using 3-NN Classifier
y_hat = neighbors.predict(X_test)
y_hat[0:5]

array([False, False, False, False,  True])

In [12]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neighbors.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_hat))

Train set Accuracy:  0.9463414634146341
Test set Accuracy:  0.8976545842217484


In [13]:
neighbors_1 = KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)

y_hat_1 = neighbors_1.predict(X_test)

print(neighbors_1)
print(metrics.accuracy_score(y_train, neighbors_1.predict(X_train)))
print(metrics.accuracy_score(y_test, y_hat_1))

KNeighborsClassifier()
0.9292682926829269
0.8898365316275764


In [14]:
Ks = 10
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
ConfustionMx = [];
for n in range(1,Ks):
    
    #Train Model and Predict  
    neighbors = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    y_hat=neighbors.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, y_hat)

    
    std_acc[n-1]=np.std(y_hat==y_test)/np.sqrt(y_hat.shape[0])

mean_acc

array([0.89410092, 0.88628287, 0.89765458, 0.87704335, 0.88983653,
       0.88059701, 0.88770434, 0.87988628, 0.891258  ])

In [15]:
print( "The best accuracy of", mean_acc.max(), "was measured with k=", mean_acc.argmax()+1) 

The best accuracy of 0.8976545842217484 was measured with k= 3


In [16]:
print('prediction set:', y_hat_1[0:5])
print('test set:      ', y_test[0:5])

prediction set: [False False False False  True]
test set:       [False False False False  True]
